# Generated by Django 4.0.3 on 2022-04-11 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('nome_filme', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ano', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('nascimento_usuario', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono_lista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pcs.usuario')),
                ('filme_na_lista', models.ManyToManyField(related_name='favoritos', to='pcs.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('nome_diretor', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nascimento_diretor', models.CharField(max_length=255)),
                ('filme_dirigido', models.ManyToManyField(related_name='diretores', to='pcs.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('nota', models.CharField(max_length=255)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs.usuario')),
                ('filme_avaliado', models.ForeignKey(default='Nome do Filme', on_delete=django.db.models.deletion.CASCADE, to='pcs.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('nome_ator', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nascimento_ator', models.CharField(max_length=255)),
                ('filme_feito', models.ManyToManyField(related_name='atores', to='pcs.filme')),
            ],
        ),
    ]
