# Generated by Django 4.0.3 on 2022-04-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ator',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='diretor',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True),
        ),
    ]
