# Generated by Django 4.0.3 on 2022-04-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0002_ator_slug_avaliacao_slug_diretor_slug_favoritos_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ('-titulo',)},
        ),
    ]
