# Generated by Django 4.0.3 on 2022-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0003_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default='Sinopse do Filme'),
        ),
    ]
