# Generated by Django 4.0.3 on 2022-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0004_filme_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='nota',
        ),
    ]
