# Generated by Django 4.0.3 on 2022-04-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0006_usuario_bio_usuario_imagem_alter_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
    ]
