# Generated by Django 4.0.3 on 2022-04-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0007_remove_usuario_bio_remove_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ator',
            name='infos_ator',
            field=models.TextField(default='Informações sobre o(a) ator(atriz)'),
        ),
        migrations.AddField(
            model_name='diretor',
            name='infos_diretor',
            field=models.TextField(default='Informações sobre o(a) diretor(a)'),
        ),
    ]
