# Generated by Django 4.0.3 on 2022-04-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0008_ator_infos_ator_diretor_infos_diretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(default='nickname', max_length=255),
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtor', models.CharField(max_length=255, unique=True)),
                ('nascimento_diretor', models.CharField(max_length=255)),
                ('filme_produzido', models.ManyToManyField(related_name='produtores', to='pcs.filme')),
            ],
        ),
    ]
